server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #是否注册到网关
          enabled: true
          lowerCaseServiceId: true
      routes:
        #可以 增加 过滤机智 before after between等
        - id: eureka-client
          uri: http://localhost:8000/
          predicates:
            - Path=/eureka
          filters:
            - StripPrefix=1
eureka:
  instance:
    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


