server:
  port: 8003
spring:
  application:
    name: hystrix-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
feign:
  hystrix:
    enabled: true